// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricsGetter is an autogenerated mock type for the MetricsGetter type
type MetricsGetter struct {
	mock.Mock
}

// IncLinksRedirected provides a mock function with no fields
func (_m *MetricsGetter) IncLinksRedirected() {
	_m.Called()
}

// NewMetricsGetter creates a new instance of MetricsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsGetter {
	mock := &MetricsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
