services:
  web:
    container_name: web
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "prod.yaml"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: