logger_path: "config/logger.json"
grpc_server:
  host: "0.0.0.0"
  port: "50051"
  timeout: 5s
http_server:
  host: "0.0.0.0"
  port: "8085"
  timeout: 5s
  idle_timeout: 60s
migrations_path: "migrations"
access_token_ttl: 15m
refresh_token_ttl: 24h
