{
 "title": "Linkify",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Links Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "url_shortener_links_created_total",
     "legendFormat": "Created Links"
    }
   ]
  },
  {
   "title": "Total Redirects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "url_shortener_links_redirected_total",
     "legendFormat": "Redirect Count"
    }
   ]
  },
  {
   "title": "Total Deleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "url_shortener_links_deleted_total",
     "legendFormat": "Deleted Count"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(http_request_duration_seconds_sum / http_request_duration_seconds_count) by (method)",
     "legendFormat": "Avg {{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, method))",
     "legendFormat": "P95 {{method}}"
    }
   ]
  }
 ]
}