// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricsSaver is an autogenerated mock type for the MetricsSaver type
type MetricsSaver struct {
	mock.Mock
}

// IncLinksCreated provides a mock function with no fields
func (_m *MetricsSaver) IncLinksCreated() {
	_m.Called()
}

// NewMetricsSaver creates a new instance of MetricsSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsSaver {
	mock := &MetricsSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
