// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CacheDeleter is an autogenerated mock type for the CacheDeleter type
type CacheDeleter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, key
func (_m *CacheDeleter) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCacheDeleter creates a new instance of CacheDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheDeleter {
	mock := &CacheDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
