// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricsDeleter is an autogenerated mock type for the MetricsDeleter type
type MetricsDeleter struct {
	mock.Mock
}

// IncLinksDeleted provides a mock function with no fields
func (_m *MetricsDeleter) IncLinksDeleted() {
	_m.Called()
}

// NewMetricsDeleter creates a new instance of MetricsDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsDeleter {
	mock := &MetricsDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
