name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Download dependencies
        working-directory: ./shortener
        run: |
          go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: ./shortener

      - name: Test
        working-directory: ./shortener
        run: |
          go test -v -race -parallel 5 -shuffle=on -coverprofile=./cover.out -covermode=atomic ./...

      - name: Check coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: shortener/cover.out